nelmio_cors:
    defaults:
        allow_origin: ['https://wikidefi.fr'] # Remplacez par votre URL front
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Authorization']
        max_age: 3600
    paths:
        '^/': # Toutes les routes
            allow_origin: ['https://wikidefi.fr']
            allow_headers: ['Content-Type', 'Authorization']
            allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
