name: Deploy to IONOS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Vérifier le code du dépôt
    - name: Checkout repository
      uses: actions/checkout@v3

    # Installer les dépendances et construire le backend
    - name: Build backend
      run: |
        cd wiki-back
        npm ci
        npm run build
        cd ..

    # Archiver les fichiers construits
    - name: Archive build files
      run: |
        tar -czf wiki-back.tar.gz wiki-back/

    # Configurer SSH pour se connecter au serveur
    - name: Setup SSH
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "${SSH_PRIVATE_KEY}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H access-5016847966.webspace-host.com >> ~/.ssh/known_hosts

    # Transférer les fichiers archivés sur le serveur
    - name: Transfer build to server
      run: |
        scp wiki-back.tar.gz a1543162@access-5016847966.webspace-host.com:~/wikidefi/

    # Déployer et démarrer le serveur
    - name: Deploy and start server
      env:
        NODE_VERSION: 18.20.5
      run: |
        ssh -tt a1543162@access-5016847966.webspace-host.com << 'EOF'
        set -e

        # Aller dans le dossier de déploiement
        cd ~/wikidefi

        # Extraire les fichiers
        tar -xzf wiki-back.tar.gz
        rm wiki-back.tar.gz

        # Vérifier NVM et Node.js
        export NVM_DIR="$HOME/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
        nvm install $NODE_VERSION
        nvm use $NODE_VERSION

        # Vérifications
        node -v
        npm -v

        # Arrêter l'ancien serveur
        pkill -f "node server.js" || echo "No existing server process to stop."

        # Démarrer le serveur en arrière-plan
        cd wiki-back
        nohup node server.js > output.log 2>&1 &
        echo "Server started successfully."
        EOF
