name: Deploy to IONOS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Vérifier le code du dépôt
    - name: Checkout repository
      uses: actions/checkout@v3

    # Installer les dépendances backend et construire le backend localement
    - name: Install backend dependencies and build
      run: |
        cd wiki-back
        npm install
        npm run build || echo "Build step failed or skipped"
        cd ..

    # Configurer SSH pour se connecter au serveur
    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H access-5016847966.webspace-host.com >> ~/.ssh/known_hosts

    # Déployer uniquement si le dossier dist existe
    - name: Deploy backend to server
      if: success() && runner.os == 'Linux'
      run: |
        if [ -d "./wiki-back/dist" ]; then
          rsync -avz --delete ./wiki-back/dist/ a1543162@access-5016847966.webspace-host.com:~/wikidefi/wiki-back/dist
        else
          echo "Backend dist folder not found, skipping deployment"
        fi

    # Démarrer ou redémarrer le backend avec PM2
    - name: Start backend with PM2
      run: |
        ssh -tt a1543162@access-5016847966.webspace-host.com << 'EOF'
        set -e
        cd ~/wikidefi/wiki-back
        if ! command -v pm2 &> /dev/null; then
          echo "PM2 is not installed. Installing..."
          npm install -g pm2
        fi
        pm2 start dist/server.js --name "wiki-backend" || pm2 restart "wiki-backend"
        pm2 save
        EOF
