name: Deploy Symfony API to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Étape 1: Cloner le dépôt
      - name: Checkout the repository
        uses: actions/checkout@v3


      # Étape 4: Déployer sur le serveur via SSH
      - name: Deploy to Server
        id: deploy_step
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/wikidefi
            git stash | git pull 

     
