name: Deploy to IONOS

on:
  push:
    branches:
      - main # Déclenche le workflow sur un push dans la branche main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Vérifier le code du dépôt
    - name: Checkout repository
      uses: actions/checkout@v3

    # Installer les dépendances backend et construire le backend localement
    - name: Install backend dependencies and build
      run: |
        cd wiki-back
        npm install
        npm run build
        cd ..

    # Configurer SSH pour se connecter au serveur
    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H access-5016847966.webspace-host.com >> ~/.ssh/known_hosts

    # Déployer le backend et le frontend statique sur le serveur
    - name: Deploy backend and frontend to server
      run: |
        rsync -avz --exclude 'node_modules' --exclude '.git' ./wiki-back a1543162@access-5016847966.webspace-host.com:~/wikidefi/wiki-back
        rsync -avz ./wiki-front/ a1543162@access-5016847966.webspace-host.com:~/wikidefi/wiki-front

    # Installer les dépendances backend sur le serveur pour des environnements spécifiques
    - name: Install server-specific backend dependencies
      run: |
        ssh a1543162@access-5016847966.webspace-host.com << 'EOF'
        set -e
        cd ~/wikidefi/wiki-back
        npm install --only=production
        EOF

    # Démarrer ou redémarrer le backend avec pm2
    - name: Start backend with PM2
      run: |
        ssh a1543162@access-5016847966.webspace-host.com << 'EOF'
        set -e
        cd ~/wikidefi/wiki-back
        if ! command -v pm2 &> /dev/null; then
          echo "PM2 is not installed. Installing..."
          npm install -g pm2
        fi
        pm2 start server.js --name "wiki-backend" || pm2 restart "wiki-backend"
        pm2 save
        EOF
