name: Deploy to IONOS

on:
  push:
    branches:
      - main # Déclenche le workflow sur un push dans la branche main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Vérifier le code du dépôt
    - name: Checkout repository
      uses: actions/checkout@v3

    # Installer les dépendances backend et construire le backend localement
    - name: Install backend dependencies and build
      run: |
        cd wiki-back
        npm install
        npm run build
        cd ..

    # Installer les dépendances frontend (si nécessaire) et construire le frontend localement
    - name: Build frontend
      run: |
        cd wiki-front
        npm install || echo "No dependencies required for frontend"
        npm run build || echo "No build step required for frontend"
        cd ..

    # Configurer SSH pour se connecter au serveur
    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H access-5016847966.webspace-host.com >> ~/.ssh/known_hosts

    # Déployer le backend (pré-compilé) et le frontend statique sur le serveur
    - name: Deploy to server
      run: |
        rsync -avz --delete ./wiki-back/dist/ a1543162@access-5016847966.webspace-host.com:~/wikidefi/wiki-back/dist
        rsync -avz --delete ./wiki-front/dist/ a1543162@access-5016847966.webspace-host.com:~/wikidefi/wiki-front

    # Démarrer ou redémarrer le backend avec PM2
    - name: Start backend with PM2
      run: |
        ssh -tt a1543162@access-5016847966.webspace-host.com << 'EOF'
        set -e
        cd ~/wikidefi/wiki-back
        if ! command -v pm2 &> /dev/null; then
          echo "PM2 is not installed. Installing..."
          curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
          apt-get install -y nodejs
          npm install -g pm2
        fi
        pm2 start dist/server.js --name "wiki-backend" || pm2 restart "wiki-backend"
        pm2 save
        EOF
