name: Deploy to IONOS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Vérifier le code du dépôt
    - name: Checkout repository
      uses: actions/checkout@v3

    # Installer les dépendances localement
    - name: Install backend dependencies locally
      run: |
        cd wiki-back
        npm install --production
        cd ..

    # Configurer SSH pour se connecter au serveur
    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H access-5016847966.webspace-host.com >> ~/.ssh/known_hosts

    # Archiver les fichiers du backend avec node_modules
    - name: Archive backend files
      run: |
        tar -czf wiki-back.tar.gz wiki-back/

    # Transférer les fichiers archivés sur le serveur
    - name: Transfer archive to server
      run: |
        scp wiki-back.tar.gz a1543162@access-5016847966.webspace-host.com:~/wikidefi/

    # Déployer l'application sur le serveur
    - name: Extract archive and deploy on server
      run: |
        ssh -tt a1543162@access-5016847966.webspace-host.com << 'EOF'
        set -e
        cd ~/wikidefi
        tar -xzf wiki-back.tar.gz
        rm wiki-back.tar.gz
        cd wiki-back
        if ! command -v pm2 &> /dev/null; then
          echo "PM2 is not installed. Installing..."
          npm install -g pm2
        fi
        pm2 start server.js --name "wikidefi-backend" || pm2 restart "wikidefi-backend"
        pm2 save
        EOF
