name: Deploy to IONOS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Vérifier le code du dépôt
    - name: Checkout repository
      uses: actions/checkout@v3

    # Installer les dépendances localement
    - name: Install dependencies locally
      run: |
        cd wiki-back
        npm install --production
        cd ..

    # Archiver les fichiers du backend
    - name: Archive backend files
      run: |
        tar -czf wiki-back.tar.gz wiki-back/

    # Configurer SSH pour se connecter au serveur
    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H access-5016847966.webspace-host.com >> ~/.ssh/known_hosts

    # Transférer les fichiers archivés sur le serveur
    - name: Transfer archive to server
      run: |
        scp wiki-back.tar.gz a1543162@access-5016847966.webspace-host.com:~/wikidefi/

    # Extraire les fichiers et démarrer le serveur avec nohup
    - name: Extract archive and start server
      run: |
        ssh -tt a1543162@access-5016847966.webspace-host.com << 'EOF'
        set -e
        cd ~/wikidefi
        tar -xzf wiki-back.tar.gz
        rm wiki-back.tar.gz
        cd wiki-back
        # Arrêter tout serveur Node.js déjà en cours d'exécution
        pkill -f "node server.js" || echo "No existing server process to stop."
        # Démarrer le serveur en arrière-plan
        nohup node server.js > output.log 2>&1 &
        echo "Server started successfully."
        EOF
